package main;
use strict;
use warnings;
use JSON;
use Encode;
use HttpUtils;
use Scalar::Util qw(looks_like_number);

sub MEROSS_DEVICE_Initialize($) {
	my ($hash) = @_;

	$hash->{DefFn} = 'MEROSS_DEVICE_Define';
	$hash->{UndefFn} = 'MEROSS_DEVICE_Undef';
	$hash->{SetFn} = 'MEROSS_DEVICE_Set';
	$hash->{AttrFn} = 'MEROSS_DEVICE_Attr';
}

sub MEROSS_DEVICE_Define($$) {
	my ($hash, $def) = @_;
	my @param = split('[ \t]+', $def);
	my $name = $hash->{NAME};

	if(int(@param) != 3) {
		return "wrong number of parameters: define <name> MEROSS_DEVICE <deviceId>";
	}

	$hash->{name} = $param[0];
	$hash->{deviceId} = $param[2];
#	$attr{$name}{devStateIcon} = 'DEFAULT_OPERATION:nibe_mode_default@green AWAY_FROM_HOME:nibe_mode_away@yellow VACATION:nibe_mode_vacation@red';
#	$attr{$name}{icon} = "nibe_heatpump";

	return undef;
}

sub MEROSS_DEVICE_Undef($$) {
	my ( $hash, $name) = @_;
	DevIo_CloseDev($hash);
	RemoveInternalTimer($hash);
	return undef;
}

sub MEROSS_DEVICE_Delete ($$) {
	my ( $hash, $name ) = @_;
	# nothing to do
	return undef;
}

sub MEROSS_DEVICE_Set($@) {
	my ($hash, $name, $cmd, @args) = @_;

	return "\"set $name\" needs at least one argument" unless(defined($cmd));

	if (ReadingsVal($name, ".access_token", "") eq "") {
		if ($cmd eq "accessCode") {
			NIBE_HEATPUMP_requestToken($hash, $args[0]);
		} else {
			return "Unknown argument $cmd, choose one of accessCode" ;
		}
	} elsif (!exists $attr{$name}{systemId}) {
		if ($cmd eq "systemId") {
			$attr{$name}{systemId} = $args[0];
			InternalTimer(gettimeofday() + $attr{$hash->{NAME}}{refreshInterval}, "NIBE_HEATPUMP_refresh", $hash);
		} else {
			return "Unknown argument $cmd, choose one of systemId" ;
		}
	} else {
		if ($cmd eq "refresh") {
			NIBE_HEATPUMP_refresh($hash);
		} elsif ($cmd eq "refreshSoftware") {
			NIBE_HEATPUMP_refreshSoftware($hash);
		} elsif ($cmd eq "mode") {
			if ($args[0] =~ m/(DEFAULT_OPERATION|AWAY_FROM_HOME|VACATION)/) {
				NIBE_HEATPUMP_setSmartHomeMode($hash, $args[0]);
			} else {
				return "Unknown value $args[0] for $cmd, choose one of DEFAULT_OPERATION AWAY_FROM_HOME VACATION";
			}
		} else {
			return "Unknown argument $cmd, choose one of mode:DEFAULT_OPERATION,AWAY_FROM_HOME,VACATION refresh:noArg refreshSoftware:noArg";
		}
	}
}

sub MEROSS_DEVICE_Attr(@) {
	my ($cmd,$name,$attr_name,$attr_value) = @_;
	if($cmd eq "set") {

	}
	return undef;
}

1;

=pod
=item device

=begin html

<a name="MEROSS_DEVICE"></a>
<h3>MEROSS_DEVICE</h3>
<ul>
	<i>MEROSS_DEVICE</i> implements a binding to meross_iot</a>.
	<br><br>
	<a name="MEROSS_DEVICE_Define"></a>
	<b>Define</b>
	<ul>
		<code>define &lt;name&gt;  MEROSS_DEVICE &lt;deviceId&gt; </code><br><br>
		&lt;deviceId&gt; specifies the <i>Identifier</i> from your MEROSS UI
		<br><br>
		Example: <br>
		<code>define MySwittch MEROSS_DEVICE 8s23vf8sw2s</code>
	</ul>
	<br>

	<a name="MEROSS_DEVICE_Set"></a>
	<b>Set</b><br>
	<ul>
		<code>set &lt;name&gt; &lt;option&gt; &lt;value&gt;</code>
		<br><br>
		You can <i>set</i> any value to any of the following options.
		<br><br>
		Options:
		<ul>
			<li><i>accessCode</i><br>
				When initializing the module you need to pass a code generated by NIBE Uplink. You will get that code by visiting the website with URL from Reading <i>accessCodeUrl</i>.
			</li><br>
			<li><i>systemId</i><br>
				When initializing the module you neet to pass the ID of your system. To get your ID visit <a href="https://www.nibeuplink.com/">NIBE Uplink</a> and select your system. Then you will see a URL like <i>https://www.nibeuplink.com/System/<b>&lt;systemID&gt;</b>/Status/Overview</i>.
			</li><br>
			<li><i>refresh</i><br>
				Reload all Readings from NIBE Uplink. No arguments are required.
			</li><br>
			<li><i>mode</i><br>
				Set the SmartHome mode of your heatpump. Possible values are <code>DEFAULT_OPERATION</code>, <code>AWAY_FROM_HOME</code> and <code>VACATION</code>.
			</li><br>
		</ul>
	</ul>
	<br>

	<a name="NIBE_HEATPUMP_Attr"></a>
	<b>Attributes</b>
	<ul>
		<code>attr &lt;name&gt; &lt;attribute&gt; &lt;value&gt;</code>
		<br><br>
		Attributes:
		<ul>
			<li><i>systemId</i> numeric<br>
				When initializing the module you neet to pass the ID of your system. To get your ID visit <a href="https://www.nibeuplink.com/">NIBE Uplink</a> and select your system. Then you will see a URL like <i>https://www.nibeuplink.com/System/<b>&lt;systemID&gt;</b>/Status/Overview</i>.
			</li><br>
			<li><i>refreshInterval</i> seconds<br>
				Seconds to next refresh of all Readings.
			</li><br>
			<li><i>maxNotifications</i> numeric<br>
				Maximum number of notifications that will be requested from NIBE Uplink.
			</li><br>
		</ul>
	</ul>
</ul>

=end html

=cut
